#!/usr/bin/env python

atom = '''
C  0.  0.  .7
C  0.  0. -.7
'''

system = {'basis': '631g', 'symmetry': 'd2h', 'frozen': True, 'irrep_nelec': {'Ag': 4, 'B1u': 4, 'B2u': 2, 'B3u': 2}}

model = {'method': 'fci'}
target = {'energy': True}
ref = {'method': 'casci', 'active': 'manual', 'select': [2, 3, 4, 5, 6, 7, 8, 9]}
state = {'wfnsym': 'ag', 'root': 0}
extra = {'pi_prune': True}
thres = {'init': 1.0e-10, 'relax': 5.0}

