#!/usr/bin/env python

atom = '''
O  0.00000000  0.00000000  0.10840502
H -0.75390364  0.00000000 -0.47943227
H  0.75390364  0.00000000 -0.47943227
'''

system = {'basis': '631g', 'symmetry': 'c1', 'frozen': True}

model = {'method': 'fci'}
target = {'energy': True}
ref = {'method': 'casci', 'select': []}
orbs = {'type': 'local'}
thres = {'inc': 5e-5}

