#!/usr/bin/env python

atom = '''
C  0.  0.  .7
C  0.  0. -.7
'''

system = {'basis': '631g', 'symmetry': 'd2h', 'frozen': True, 'irrep_nelec': {'Ag': 4, 'B1u': 4, 'B2u': 2, 'B3u': 2}}

model = {'method': 'fci'}
target = {'energy': True}
ref = {'method': 'casscf', 'active': 'manual', 'select': [2, 3, 4, 5, 6, 7, 8, 9], 'wfnsym': ('Ag', 'Ag', 'Ag', 'B1g'), 'weights': (.25, .25, .25, .25), 'hf_guess': False}
state = {'wfnsym': 'ag', 'root': 0}
thres = {'inc': 1e-5}

