#!/usr/bin/env python

atom = '''
O  0.00000000  0.00000000  0.10840502
H -0.75390364  0.00000000 -0.47943227
H  0.75390364  0.00000000 -0.47943227
'''

system = {'basis': '631g', 'symmetry': 'c2v', 'frozen': True}

model = {'method': 'fci'}
target = {'energy': True}
base = {'method': 'ccsd(t)'}
ref = {'method': 'casci', 'select': [1, 2, 3, 4]}
state = {'wfnsym': 'a1', 'root': 0}
thres = {'init': 1.0e-10, 'relax': 25.0}

