#!/usr/bin/env python

atom = '''
O  0.00000000  0.00000000  0.10840502
H -0.75390364  0.00000000 -0.47943227
H  0.75390364  0.00000000 -0.47943227
'''

system = {'basis': '631g', 'symmetry': 'c2v'}

model = {'method': 'fci'}
target = {'energy': True}
prot = {'scheme': 2}
base = {'method': 'ccsd(t)'}
ref = {'method': 'casci', 'select': [0, 1, 2, 3, 4, 5, 6]}
orbs = {'type': 'ccsd'}
thres = {'init': 1.0e-10, 'relax': 10.0}

