name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: "openmpi"
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        sudo apt-get -qq install libblas-dev
        python -m pip install --upgrade pip
        pip install numpy scipy h5py mpi4py seaborn pytest pytest-cov mypy pyscf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Fetch MBECC library
      run: |
        gh release download --repo eriksen-lab/mbecc --pattern libmbecc.so
        echo "MBECCLIB = 'libmbecc.so'" > pymbe/settings.py
      env:
        GITHUB_TOKEN: ${{ secrets.MBECC_Release_Access }}
      shell: bash

    - name: Type checking
      run: mypy --ignore-missing-imports --warn-redundant-casts pymbe
        
    - name: Testing
      run: |
        export PYTHONHASHSEED=0
        python3 -m pytest -x --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
